# Generated by Django 2.2.6 on 2019-10-31 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.IntegerField(max_length=8)),
                ('issue_date', models.DateTimeField(verbose_name='issue date')),
                ('return_date', models.DateTimeField(verbose_name='return date')),
                ('fine_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('email_add', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('student_id', models.IntegerField(max_length=10)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Books_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=60)),
                ('catagory', models.CharField(max_length=20)),
                ('auther_name', models.CharField(max_length=20)),
                ('book_edition', models.IntegerField(default=1)),
                ('book_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Book_Issue')),
            ],
        ),
        migrations.AddField(
            model_name='book_issue',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.User'),
        ),
    ]
